platform:ios, '13.0'
use_frameworks!

target 'CartoonWorld' do
  pod 'AFNetworking', '~> 4.0.1'
  pod 'MJRefresh', '~> 3.7.6'
  pod 'SDWebImage', '~> 5.18.7'
  pod 'Masonry', '~> 1.1.0'
  pod 'MJExtension', '~> 3.4.1'
  pod 'DZRPageMenuController', '~> 1.1.3'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'SDCycleScrollView', '~> 1.82'
  pod 'JRSwizzle'
  pod 'TZImagePickerController'
  pod 'Realm', '~> 10.44.0'
end
